### ISSUE TITLE
How to add Button in lanes i need to add one more button beside the add card Button

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#235] opened 2019-06-04 09:17 UTC

**Comment by JavaJamie** [comment] 2019-06-04 14:39
You can do something like the following:

`                    addCardLink={<div><button>Add card</button<button>Button 2</button></div>}
`

**Comment by mehuljariwala** [comment] 2019-06-05 04:22
Thanks @JavaJamie 
did you know how can i change lanes bg color ?

**Comment by JavaJamie** [comment] 2019-06-05 08:09
You can use the following class:

`.react-trello-lane {
    background-color: red !important;
}`

**Comment by mehuljariwala** [comment] 2019-06-05 15:34
I added one button beside that but on i do this its calling same Add card function but i need to call btn2Click function.

```
btn2Click =() =>{
console.log('hi');
}
addCardLink={<div><button>Add card</button<button onClick={this.btn2Click}>Button 2</button></div>}
```

**Comment by dapi** [comment] 2019-07-01 20:29
@mehuljariwala hi!

I have just  done Dependency Injection mechanism. Could you please test it and give me a feedback?

https://github.com/rcdexta/react-trello/pull/274

```
yarn add BrandyMint/react-trello#components_dependency_injections
```

You could try to customise `AddCardLink` component.

If it is Ok, I will merge it to master.

**Comment by dapi** [comment] 2019-07-15 11:06
Now dependency injection in master. Try it https://github.com/rcdexta/react-trello#3-completely-customize-the-look-and-feel-by-using-components-dependency-injection

**Comment by dapi** [comment] 2019-07-15 11:12
This issue is duplicate of https://github.com/rcdexta/react-trello/issues/183

**Closed by dapi** 2019-07-15 11:12 UTC
Labels: pending to close
