### ISSUE TITLE
Cannot find module: 'rt/styles/Base'. Make sure this package is installed.

### ISSUE THREAD

**Issue by tanmay-keystride** [rcdexta/react-trello#361] opened 2020-03-11 09:08 UTC
While deploying the project on Netlify I am facing this issue because the internal components refer to each other using "rt" instead of "react-trello"

**Comment by luizfilipefc-sp** [comment] 2020-03-12 17:18
It seems that you're using it in a different way, I got the same problem but I was calling the import wrongly, the correct statement should be `import Board from 'react-trello'`

**Comment by jprosevear** [comment] 2020-03-16 19:30
This is a duplicate of #359

**Comment by rcdexta** [comment] 2020-04-04 19:26
Closed in https://github.com/rcdexta/react-trello/releases/tag/v2.2.5 Thanks for the comments @jprosevear

**Closed** 2020-04-04 19:27 UTC
