### ISSUE TITLE
Module not found: Can't resolve 'rt/styles/Base' 

### ISSUE THREAD

**Issue by marciowelben** [rcdexta/react-trello#362] opened 2020-03-12 19:34 UTC
When trying to run the application I'm getting this error

I tried to set an module-resolver for the rt but still error

```
{
        test: /\.(js|jsx)$/,
        include: paths.appSrc,
        loader: require.resolve('babel-loader'),
        exclude: /node_modules/,
        query: {
          presets: ['@babel/preset-env', '@babel/preset-react'],
          plugins: [
            ['import', { libraryName: 'antd', style: true }],
            ['@babel/plugin-proposal-class-properties', { loose: true }],
            [
              'module-resolver',
              {
                rt: ['./src']
              }
            ]
          ],
          cacheDirectory: true
        }
      },
```

**Comment by marciowelben** [comment] 2020-03-12 19:51
using `import Board from 'react-trello/dist'` should solve until they fix

**Comment by jprosevear** [comment] 2020-03-16 19:31
This is a duplicate of #359

**Comment by rcdexta** [comment] 2020-04-04 19:26
Closed in https://github.com/rcdexta/react-trello/releases/tag/v2.2.5

**Closed by rcdexta** 2020-04-04 19:26 UTC
