### ISSUE TITLE
Can I drag lane to reorder lanes？

### ISSUE THREAD

**Issue by changyu72** [rcdexta/react-trello#83] opened 2018-04-21 14:10 UTC
Can I drag lane to reorder lanes？

**Comment by rcdexta** [comment] 2018-04-22 06:04
Currently, drag-n-drop for lanes is not supported.

Tracked here: https://github.com/rcdexta/react-trello/issues/30

Hoping to add it soon!

**Comment by rcdexta** [comment] 2018-04-22 06:05
Duplicate of https://github.com/rcdexta/react-trello/issues/30

**Closed by rcdexta** 2018-04-22 06:05 UTC

**Comment by changyu72** [comment] 2018-04-22 06:12
Oh, looking forward to it, thank you！
