### ISSUE TITLE
TypeError: Cannot read property 'GlobalStyle' of undefined on Release 2.2.3

### ISSUE THREAD

**Issue by fsa317** [rcdexta/react-trello#346] opened 2020-01-20 03:45 UTC
When using Release 2.2.3 I get the following error on startup:

`TypeError: Cannot read property 'GlobalStyle' of undefined`

The code is pretty simple:

```
class App extends Component {

  render() {
    return (
      <div>
        <Board editable 
        data={data} />
      </div>
    )
  }
}
```

What's interesting is that if I switch the dependency to react-trello 2.1.3 and do npm install, npm start it works.

More specifically, the break seems to happen between 2.1.4 and 2.2.0

**Comment by rcdexta** [comment] 2020-04-04 19:33
Positively fixed in 2.2.5. Please reopen issue if you see further discrepancies

**Closed by rcdexta** 2020-04-04 19:33 UTC

**Comment by martijnc94** [comment] 2020-04-08 09:24
When using release 2.2.5 in a basic asp.net core react app, I get the same error as stated before.

**Comment by kblazelek** [comment] 2020-04-18 11:21
I have the same error while using React template for ASP.NET Core app in Visual Studio 2019. For some weird reason it's caused by the way react-trello is imported.
This works:
`import Board from 'react-trello'`
This doesn't:
`import { Board } from 'react-trello'`

**Comment by bhaveshbusa** [comment] 2020-05-02 20:44
> I have the same error while using React template for ASP.NET Core app in Visual Studio 2019. For some weird reason it's caused by the way react-trello is imported.
> This works:
> `import Board from 'react-trello'`
> This doesn't:
> `import { Board } from 'react-trello'`

Thanks, This worked for me. I don't know what is the underlying reason.

**Comment by bhaveshbusa** [comment] 2020-05-03 07:03
> > I have the same error while using React template for ASP.NET Core app in Visual Studio 2019. For some weird reason it's caused by the way react-trello is imported.
> > This works:
> > `import Board from 'react-trello'`
> > This doesn't:
> > `import { Board } from 'react-trello'`
> 
> Thanks, This worked for me. I don't know what is the underlying reason.

After some more searching, I think I was getting error as I was used named export instead of default export.

To test named export I changed to 

`import { default as Board } from 'react-trello'`
