### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lyihongl** [rcdexta/react-trello#363] opened 2020-03-18 04:46 UTC
**Describe the bug**
No idea why there is a syntax error here.

**To Reproduce**
```
function Test(){
const data = {
  lanes: [
    {
      id: 'lane1',
      title: 'Planned Tasks',
      label: '2/2',
      cards: [
        {id: 'Card1', title: 'Write Blog', description: 'Can AI make memes', label: '30 mins', draggable: false},
        {id: 'Card2', title: 'Pay Rent', description: 'Transfer via NEFT', label: '5 mins', metadata: {sha: 'be312a1'}}
      ]
    },
    {
      id: 'lane2',
      title: 'Completed',
      label: '0/0',
      cards: []
    }
  ]
}
return(
    <div>
      <Board data={data} />
    </div>
  );
}
```

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/35238597/76925740-d842a300-68b0-11ea-9df9-2ed1dda4a7ba.PNG)

**Desktop (please complete the following information):**
 - OS: Xubuntu (Ubuntu 18.04.2 LTS base)
 - Browser: Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
I ran the install command, and just tried the basic example. Not sure why there is a syntax error as everything looks in order. Sorry if this is dumb I'm pretty new to react.

**Comment by jprosevear** [comment] 2020-03-22 14:50
Likely a duplicate of #359

**Comment by ChenMorSays** [comment] 2020-04-03 13:02
Got the same problem. Anyone has an idea?

**Comment by ChenMorSays** [comment] 2020-04-03 13:04
Experiencing this problem too. Exploring a solution.

**Comment by jprosevear** [comment] 2020-04-03 13:21
The workaround is to import from react-trello/dist

I have a PR in #360

**Comment by ChenMorSays** [comment] 2020-04-03 13:52
You're a genius! Thank you.

**Comment by rcdexta** [comment] 2020-04-04 19:25
Sorry about the late turnaround on this one. v2.2.5 should fix the direct root cause.

**Closed by rcdexta** 2020-04-04 19:25 UTC
